# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Windows Qt6 Build with Custom OpenCV

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # 1. Install Qt 6.10.1 for Windows
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64' # Standard for Qt 6 on Windows

    # 2. Set up MSVC (Visual Studio Compiler)
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

# 3. Download and Unzip your Custom OpenCV
    - name: Download Custom OpenCV
      shell: pwsh
      run: |
        # 1. Download the zip from your release tag
        gh release download v1.0-deps --pattern "build2.zip" --repo ${{ github.repository }}
        
        # 2. Unzip it
        Expand-Archive -Path "build2.zip" -DestinationPath "C:\custom_deps" -Force

    - name: List Files (Debug Step)
      shell: pwsh
      run: |
        # This will show us exactly where the .cmake file is
        Get-ChildItem -Path "C:\custom_deps" -Recurse -Filter "OpenCVConfig.cmake" | Select-Object FullName

    - name: Configure CMake
      run: |
        # We start with the base folder. 
        # If the 'List Files' step shows it's deeper, we will adjust this path next.
        cmake -B build `
        -DCMAKE_BUILD_TYPE=Release `
        -DOpenCV_DIR="C:\custom_deps"
